name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or the branch you want to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t Menna114/booster-ci-cd-project .

      - name: Push Docker image to Docker Hub
        run: |
          docker push Menna114/booster-ci-cd-project

